# Permalinks
permalink:           pretty

# Setup
title:               Swami Venkatesh
tagline:             Swami's Attempt At A Data Science Blog
url:                 http://swv293.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Swami Venkatesh
  url:               https://www.linkedin.com/in/swaminathan-venkatesh-phd-44128128/
  email:             vswami101@yahoo.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/swv293

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
